#!/bin/bash

COUNTRY=US

## Getting command line options
while getopts 'c:' OPTION
do
  case "$OPTION" in
    c)
      COUNTRY="$OPTARG"
  esac
done
shift "$(($OPTIND -1))"

## Grabbing deaths from csv instead of an API like an asshole.
datadeaths=$(curl -s https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_global.csv)

## Grabbing cases from csv instead of an API like an asshole.
datacases=$(curl -s https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv)

## Calculating today's death rate 
dratetoday=$(echo "$datadeaths" | grep $COUNTRY | awk -F',' '{ diff = $NF - $(NF-1) ; avg = ($NF + $(NF-1)) / 2 ; print (diff / avg) * 100}')

## Calculating today's case rate 
caseratetoday=$(echo "$datacases" | grep $COUNTRY | awk -F',' '{ diff = $NF - $(NF-1) ; avg = ($NF + $(NF-1)) / 2 ; print (diff / avg) * 100}')

## Getting number of cases today
casestoday=$(echo "$datacases" | grep $COUNTRY | awk -F',' '{print $NF}')

## Getting number of deaths today
deathtoday=$(echo "$datadeaths" | grep $COUNTRY | awk -F',' '{print $NF}')

## Getting number of deaths yesterday
drateyday=$(echo "$datadeaths" | grep $COUNTRY | awk -F',' '{ for (i=1; i<=5; i++){ diff = $(NF-i) - $(NF-(i+1)); avg = ($(NF-i) + $(NF-(i+1))) / 2 ; printf (diff / avg) * 100"%% "}}')

## Getting number of cases yesterday
caserateyday=$(echo "$datacases" | grep $COUNTRY | awk -F',' '{ for (i=1; i<=5; i++){ diff = $(NF-i) - $(NF-(i+1)); avg = ($(NF-i) + $(NF-(i+1))) / 2 ; printf (diff / avg) * 100"%% "}}')

## Getting number of death rate
avgdrate=$(echo "$datadeaths" | grep $COUNTRY | awk -F',' '{ for (i=0; i<=6; i++){ diff = $(NF-i) - $(NF-(i+1)); avg = ($(NF-i) + $(NF-(i+1))) / 2 ; print (diff / avg) * 100}}' | awk '{ total += $1; count++ } END { print total/count }')

## Getting number of death rate
avgcaserate=$(echo "$datacases" | grep $COUNTRY | awk -F',' '{ for (i=0; i<=6; i++){ diff = $(NF-i) - $(NF-(i+1)); avg = ($(NF-i) + $(NF-(i+1))) / 2 ; print (diff / avg) * 100}}' | awk '{ total += $1; count++ } END { print total/count }')

## Checking to make sure one of the vars is a number to make sure it worked.
if ! [[ $dratetoday =~ ^[+-]?[0-9]+\.?[0-9]*$ ]]
then
  echo "The country $COUNTRY doesn't exist or something ain't right"
  exit
fi

## Spitting all the creap out
echo "Confirmed $COUNTRY Cases: Yesterday the difference in confirmed cases from the day before was $caseratetoday %, in contrast the 5 previous days are: $caserateyday
Confirmed $COUNTRY Deaths: Yesterday the difference in confirmed deaths from the day before was $dratetoday %, in contrast the 5 previous days are $drateyday" 
echo ""
echo "The average death rate is $avgdrate % over the last 7 days"
echo "The average case rate is $avgcaserate % over the last 7 days"
echo ""

## More poop
casesinweek=$(echo "scale=5;$casestoday*(1+$avgcaserate/100)^7" | bc)
casesinmonth=$(echo "scale=5;$casestoday*(1+$avgcaserate/100)^30" | bc)

echo "using just the above averages, these are the projections if no changes to growth occur:"
echo "Current cases is $casestoday the expected cases in 7 days is $casesinweek"
echo "Current cases is $casestoday the expected cases in 30 days is $casesinmonth"
echo ""

## Even more poop
deathinweek=$(echo "scale=5;$deathtoday*(1+$avgdrate/100)^7" | bc)
deathinmonth=$(echo "scale=5;$deathtoday*(1+$avgdrate/100)^30" | bc)

echo "Current deaths are $deathtoday the expected deaths in 7 days is $deathinweek"
echo "Current deaths are $deathtoday the expected deaths in 30 days is $deathinmonth"

## Confirmation Tom is the worst.